export const DIRECTORY_ASSETS = 'assets';
export const DIRECTORY_IMAGES = DIRECTORY_ASSETS + '/images';
export const DIRECTORY_CARDS = DIRECTORY_IMAGES + '/cards';

// All images from this URL: https://en.wikipedia.org/wiki/Standard_52-card_deck
export const cards = [
    require('./assets/images/cards/club1.svg'),
    require('./assets/images/cards/club2.svg'),
    require('./assets/images/cards/club3.svg'),
    require('./assets/images/cards/club4.svg'),
    require('./assets/images/cards/club5.svg'),
    require('./assets/images/cards/club6.svg'),
    require('./assets/images/cards/club7.svg'),
    require('./assets/images/cards/club8.svg'),
    require('./assets/images/cards/club9.svg'),
    require('./assets/images/cards/club10.svg'),
    require('./assets/images/cards/clubj.svg'),
    require('./assets/images/cards/clubq.svg'),
    require('./assets/images/cards/clubk.svg'),

    require('./assets/images/cards/diamond1.svg'),
    require('./assets/images/cards/diamond2.svg'),
    require('./assets/images/cards/diamond3.svg'),
    require('./assets/images/cards/diamond4.svg'),
    require('./assets/images/cards/diamond5.svg'),
    require('./assets/images/cards/diamond6.svg'),
    require('./assets/images/cards/diamond7.svg'),
    require('./assets/images/cards/diamond8.svg'),
    require('./assets/images/cards/diamond9.svg'),
    require('./assets/images/cards/diamond10.svg'),
    require('./assets/images/cards/diamondj.svg'),
    require('./assets/images/cards/diamondq.svg'),
    require('./assets/images/cards/diamondk.svg'),

    require('./assets/images/cards/heart1.svg'),
    require('./assets/images/cards/heart2.svg'),
    require('./assets/images/cards/heart3.svg'),
    require('./assets/images/cards/heart4.svg'),
    require('./assets/images/cards/heart5.svg'),
    require('./assets/images/cards/heart6.svg'),
    require('./assets/images/cards/heart7.svg'),
    require('./assets/images/cards/heart8.svg'),
    require('./assets/images/cards/heart9.svg'),
    require('./assets/images/cards/heart10.svg'),
    require('./assets/images/cards/heartj.svg'),
    require('./assets/images/cards/heartq.svg'),
    require('./assets/images/cards/heartk.svg'),

    require('./assets/images/cards/spade1.svg'),
    require('./assets/images/cards/spade2.svg'),
    require('./assets/images/cards/spade3.svg'),
    require('./assets/images/cards/spade4.svg'),
    require('./assets/images/cards/spade5.svg'),
    require('./assets/images/cards/spade6.svg'),
    require('./assets/images/cards/spade7.svg'),
    require('./assets/images/cards/spade8.svg'),
    require('./assets/images/cards/spade9.svg'),
    require('./assets/images/cards/spade10.svg'),
    require('./assets/images/cards/spadej.svg'),
    require('./assets/images/cards/spadeq.svg'),
    require('./assets/images/cards/spadek.svg'),
];