export const DIRECTORY_ASSETS = 'assets';
export const DIRECTORY_IMAGES = DIRECTORY_ASSETS + '/images';
export const DIRECTORY_CARDS = DIRECTORY_IMAGES + '/cards';

// All images from this URL: https://en.wikipedia.org/wiki/Standard_52-card_deck
export const cards = [
    require('./assets/images/cards/club-1.svg'),
    require('./assets/images/cards/club-2.svg'),
    require('./assets/images/cards/club-3.svg'),
    require('./assets/images/cards/club-4.svg'),
    require('./assets/images/cards/club-5.svg'),
    require('./assets/images/cards/club-6.svg'),
    require('./assets/images/cards/club-7.svg'),
    require('./assets/images/cards/club-8.svg'),
    require('./assets/images/cards/club-9.svg'),
    require('./assets/images/cards/club-10.svg'),
    require('./assets/images/cards/club-j.svg'),
    require('./assets/images/cards/club-q.svg'),
    require('./assets/images/cards/club-k.svg'),

    require('./assets/images/cards/diamond-1.svg'),
    require('./assets/images/cards/diamond-2.svg'),
    require('./assets/images/cards/diamond-3.svg'),
    require('./assets/images/cards/diamond-4.svg'),
    require('./assets/images/cards/diamond-5.svg'),
    require('./assets/images/cards/diamond-6.svg'),
    require('./assets/images/cards/diamond-7.svg'),
    require('./assets/images/cards/diamond-8.svg'),
    require('./assets/images/cards/diamond-9.svg'),
    require('./assets/images/cards/diamond-10.svg'),
    require('./assets/images/cards/diamond-j.svg'),
    require('./assets/images/cards/diamond-q.svg'),
    require('./assets/images/cards/diamond-k.svg'),

    require('./assets/images/cards/heart-1.svg'),
    require('./assets/images/cards/heart-2.svg'),
    require('./assets/images/cards/heart-3.svg'),
    require('./assets/images/cards/heart-4.svg'),
    require('./assets/images/cards/heart-5.svg'),
    require('./assets/images/cards/heart-6.svg'),
    require('./assets/images/cards/heart-7.svg'),
    require('./assets/images/cards/heart-8.svg'),
    require('./assets/images/cards/heart-9.svg'),
    require('./assets/images/cards/heart-10.svg'),
    require('./assets/images/cards/heart-j.svg'),
    require('./assets/images/cards/heart-q.svg'),
    require('./assets/images/cards/heart-k.svg'),

    require('./assets/images/cards/spade-1.svg'),
    require('./assets/images/cards/spade-2.svg'),
    require('./assets/images/cards/spade-3.svg'),
    require('./assets/images/cards/spade-4.svg'),
    require('./assets/images/cards/spade-5.svg'),
    require('./assets/images/cards/spade-6.svg'),
    require('./assets/images/cards/spade-7.svg'),
    require('./assets/images/cards/spade-8.svg'),
    require('./assets/images/cards/spade-9.svg'),
    require('./assets/images/cards/spade-10.svg'),
    require('./assets/images/cards/spade-j.svg'),
    require('./assets/images/cards/spade-q.svg'),
    require('./assets/images/cards/spade-k.svg'),
];