export const DIRECTORY_ASSETS = 'assets';
export const DIRECTORY_IMAGES = DIRECTORY_ASSETS + '/images';
export const DIRECTORY_CARDS = DIRECTORY_IMAGES + '/cards';

// All images from this URL: https://en.wikipedia.org/wiki/Standard_52-card_deck
export const cards = [
    require('./assets/images/cards/club1.png'),
    require('./assets/images/cards/club2.png'),
    require('./assets/images/cards/club3.png'),
    require('./assets/images/cards/club4.png'),
    require('./assets/images/cards/club5.png'),
    require('./assets/images/cards/club6.png'),
    require('./assets/images/cards/club7.png'),
    require('./assets/images/cards/club8.png'),
    require('./assets/images/cards/club9.png'),
    require('./assets/images/cards/club10.png'),
    require('./assets/images/cards/clubj.png'),
    require('./assets/images/cards/clubq.png'),
    require('./assets/images/cards/clubk.png'),

    require('./assets/images/cards/diamond1.png'),
    require('./assets/images/cards/diamond2.png'),
    require('./assets/images/cards/diamond3.png'),
    require('./assets/images/cards/diamond4.png'),
    require('./assets/images/cards/diamond5.png'),
    require('./assets/images/cards/diamond6.png'),
    require('./assets/images/cards/diamond7.png'),
    require('./assets/images/cards/diamond8.png'),
    require('./assets/images/cards/diamond9.png'),
    require('./assets/images/cards/diamond10.png'),
    require('./assets/images/cards/diamondj.png'),
    require('./assets/images/cards/diamondq.png'),
    require('./assets/images/cards/diamondk.png'),

    require('./assets/images/cards/heart1.png'),
    require('./assets/images/cards/heart2.png'),
    require('./assets/images/cards/heart3.png'),
    require('./assets/images/cards/heart4.png'),
    require('./assets/images/cards/heart5.png'),
    require('./assets/images/cards/heart6.png'),
    require('./assets/images/cards/heart7.png'),
    require('./assets/images/cards/heart8.png'),
    require('./assets/images/cards/heart9.png'),
    require('./assets/images/cards/heart10.png'),
    require('./assets/images/cards/heartj.png'),
    require('./assets/images/cards/heartq.png'),
    require('./assets/images/cards/heartk.png'),

    require('./assets/images/cards/spade1.png'),
    require('./assets/images/cards/spade2.png'),
    require('./assets/images/cards/spade3.png'),
    require('./assets/images/cards/spade4.png'),
    require('./assets/images/cards/spade5.png'),
    require('./assets/images/cards/spade6.png'),
    require('./assets/images/cards/spade7.png'),
    require('./assets/images/cards/spade8.png'),
    require('./assets/images/cards/spade9.png'),
    require('./assets/images/cards/spade10.png'),
    require('./assets/images/cards/spadej.png'),
    require('./assets/images/cards/spadeq.png'),
    require('./assets/images/cards/spadek.png'),
];